import fs from "fs";
import path from "path";

import { fileURLToPath } from "url";
import type { AstroIntegration } from "astro";

export function postBuildCleaner(): AstroIntegration {

    // Console-compatible text formatter
    const darkOrangeText = "\x1b[38;5;208m";
    const lightOrangeBg = "\x1b[48;5;215m";
    const lightGrayText = "\x1b[90m";
    const resetColor = "\x1b[0m";
    const regularHOOK = `${lightGrayText}${new Date().toLocaleTimeString('en-GB')}${resetColor} ${darkOrangeText}[HOOK]${resetColor}`;
    const orangeCHECK = `${darkOrangeText}✓${resetColor}`;
    const orangePLAY = `${darkOrangeText}▶${resetColor}`;

    return {
        name: "post-build-cleaner",
        hooks: {
            "astro:build:done": async ({ dir }) => {
                // Hook starting notice
                console.log(`\n${darkOrangeText}${lightOrangeBg} Running custom Astro Hooks ${resetColor}`)
                console.log(`${regularHOOK} ${darkOrangeText}Initializing PostBuildCleaner...${resetColor}\n`);

                // Path generator
                const distPath = (target: string):string => path.join(fileURLToPath(dir), target);

                // Target Folders
                const assetsDir = distPath("_astro");
                const wellKnownDir = distPath(".well-known");
                const wellKnownWkdHuDir = path.join(wellKnownDir, "openpgpkey", "hu");
                const openpgpDir = distPath("openpgp");

                // Target files
                const sourceSecurity = distPath("security.txt");
                const sourceWebfinger = distPath("webfinger.json");

                // WELL-KNOWN FOLDER TREATMENT (INCLUDES SECURITY.TXT & WEBFINGER)
                // Create .well-known directory (doesn't exist post-build)
                if (!fs.existsSync(wellKnownDir)) fs.mkdirSync(wellKnownDir, { recursive: true });

                // Move security.txt
                if (fs.existsSync(sourceSecurity)) {
                    fs.renameSync(sourceSecurity, path.join(wellKnownDir, "security.txt"));
                    console.log(`${regularHOOK} ${orangeCHECK} Moved: /dist/.well-known/security.txt`);
                }

                // Move and strip extension from webfinger.json
                if (fs.existsSync(sourceWebfinger)) {
                    fs.renameSync(sourceWebfinger, path.join(wellKnownDir, "webfinger"));
                    console.log(`${regularHOOK} ${orangeCHECK} Moved & Stripped: /dist/.well-known/webfinger (Extensionless)\n`)
                }

                // Openpgp treatment
                if (fs.existsSync(openpgpDir)) {
                    // Create the final nested subdirectories inside .well-known/
                    fs.mkdirSync(wellKnownWkdHuDir, { recursive: true });

                    // Move WKD policy file
                    const sourcePolicy = path.join(openpgpDir, "policy");
                    if (fs.existsSync(sourcePolicy)) {
                        fs.renameSync(sourcePolicy, path.join(wellKnownDir, "openpgpkey", "policy"));
                        console.log(`${regularHOOK} ${orangeCHECK} Moved WKD Policy: /dist/.well-known/openpgpkey/policy (Extensionless)`);
                    }

                    // Move autogenerated WKD hashes appropriately
                    const sourceHuDir = path.join(openpgpDir, "hu");
                    if (fs.existsSync(sourceHuDir)) {
                        fs.readdirSync(sourceHuDir).forEach(hashFile => {
                            const currentFilePath = path.join(sourceHuDir, hashFile);
                            
                            // Ensure it is a file, not a stray directory
                            if (fs.statSync(currentFilePath).isFile()) {
                                fs.renameSync(currentFilePath, path.join(wellKnownWkdHuDir, hashFile));
                                console.log(`${regularHOOK} ${orangeCHECK} Moved WKD Hash: /dist/.well-known/openpgpkey/hu/${hashFile}`);
                            }
                        });
                    }
                    // Clean up the temporary source directory completely
                    fs.rmSync(openpgpDir, { recursive: true, force: true });
                    console.log(`${regularHOOK} ${orangeCHECK} Removed previous OpenPGP Page from Source\n`);
                }

                // _ASTRO ASSETS TREATMENT (FOR UNOPTIMIZED IMAGES)
                // Delete unoptimized picture files from _astro
                if (fs.existsSync(assetsDir)) {
                    console.log(`${regularHOOK} Purging unoptimized source image:`);
                    let index = 1;
                    
                    fs.readdirSync(assetsDir).forEach(file => {
                        const isUnoptimized = [".png", ".jpg", ".jpeg"].includes(path.extname(file).toLowerCase());

                        if (isUnoptimized) {
                            fs.unlinkSync(path.join(assetsDir, file));
                            console.log(`${regularHOOK} ${orangePLAY} (${index++}): _astro/${file}`);
                        }
                    });
                }
                console.log(`\n${regularHOOK} ${orangeCHECK} ${darkOrangeText}PostBuildCleaner Sucessful${resetColor}\n`);
            }
        }
    };
}